import type {
  VisualizerEdge,
  VisualizerGraph,
  VisualizerNode,
  VisualizerTimelineBucket,
  VisualizerTransaction,
} from "./visualizer-types";

export const DEMO_VISUALIZER_WALLET =
  "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" as const;

const ADDRESSES = {
  pulseXRouter: "0x1715a3E4A142d8b698131108995174F37aEBA10D" as const,
  nineMmRouter: "0x283aC8639d1dF13f7b855de1A710D351f122a00F" as const,
  phuxVault: "0x6B175474E89094C44Da98b954EedeAC495271d0F" as const,
  libertySwap: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6" as const,
  hexToken: "0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39" as const,
  plsxToken: "0x95B303987A60C71504D99Aa1b13B4DA07b0790ab" as const,
  incToken: "0x2fa878Ab3F87CC1C9737Fc071108F904c0B0C95d" as const,
  wplsToken: "0xA1077a294DDE1B09BB078844DF40758a5D0f9a27" as const,
  hexPlsPair: "0xF1f955016EcbCd7321c7266BccFB96c68ea5E49b" as const,
  plsxWplsPair: "0x29eA7545DEf87022BAdc76323F373EA1e707C523" as const,
  farm: "0xFfFfFfFfD38bD0B166CC6C657f928eC7e3C2CbC8" as const,
  staking: "0x0000000000000000000000000000000000000369" as const,
  bridge: "0x9ACc1d6Aa9b846083E49742Afd5F89bD6D6b4C01" as const,
  spenderA: "0x000000000022D473030F116dDEE9F6B43aC78BA3" as const,
  spenderB: "0x1111111254EEB25477B68fb85Ed929f73A960582" as const,
  contractA: "0x0000000000000000000000000000000000000BAD" as const,
  contractB: "0x0000000000000000000000000000000000000B0B" as const,
};

export function buildDemoVisualizerGraph(
  walletAddress: `0x${string}` = DEMO_VISUALIZER_WALLET,
): VisualizerGraph {
  return {
    centerNodeId: "center-wallet",
    generatedAtLabel: "Local demo data",
    summary: {
      totalInflowLabel: "$184,420 demo",
      totalOutflowLabel: "$126,870 demo",
      tokenCountLabel: "18 demo tokens",
      plsBalanceLabel: "54,820 PLS demo",
      firstSeenLabel: "Jan 2024 demo",
      lastActiveLabel: "14m ago demo",
    },
    nodes: buildVisualizerNodes(walletAddress),
    edges: DEMO_VISUALIZER_EDGES,
    transactions: DEMO_VISUALIZER_TRANSACTIONS,
    timeline: DEMO_VISUALIZER_TIMELINE,
  };
}

function buildVisualizerNodes(
  walletAddress: `0x${string}`,
): readonly VisualizerNode[] {
  return [
    {
      id: "center-wallet",
      label: "Wallet under review",
      kind: "searched-wallet",
      address: walletAddress,
      x: 50,
      y: 50,
      volumeScore: 98,
      balanceLabel: "54.8k PLS",
      activityLabel: "86 demo tx",
      status: "review",
      confidenceLabel: "Demo center",
      description:
        "The searched address stays at the center of this local PulseChain visualizer demo.",
    },
    {
      id: "pulsex-router",
      label: "PulseX router",
      kind: "router",
      address: ADDRESSES.pulseXRouter,
      x: 31,
      y: 35,
      volumeScore: 82,
      balanceLabel: "Router",
      activityLabel: "22 demo tx",
      status: "context",
      confidenceLabel: "Known protocol label",
      description:
        "Router-style node used to show swap and approval relationships in the demo graph.",
    },
    {
      id: "nine-mm",
      label: "9mm router",
      kind: "router",
      address: ADDRESSES.nineMmRouter,
      x: 32,
      y: 63,
      volumeScore: 68,
      balanceLabel: "Router",
      activityLabel: "13 demo tx",
      status: "context",
      confidenceLabel: "Known protocol label",
      description:
        "Protocol router node for a second sample trading surface.",
    },
    {
      id: "phux",
      label: "Phux vault",
      kind: "known-protocol",
      address: ADDRESSES.phuxVault,
      x: 41,
      y: 22,
      volumeScore: 57,
      balanceLabel: "Vault",
      activityLabel: "7 demo tx",
      status: "context",
      confidenceLabel: "Demo protocol label",
      description:
        "Protocol-style node that adds a research cluster above the wallet.",
    },
    {
      id: "liberty",
      label: "LibertySwap",
      kind: "known-protocol",
      address: ADDRESSES.libertySwap,
      x: 63,
      y: 24,
      volumeScore: 48,
      balanceLabel: "DEX",
      activityLabel: "5 demo tx",
      status: "context",
      confidenceLabel: "Demo protocol label",
      description:
        "Secondary protocol node for route comparison context.",
    },
    {
      id: "hex-token",
      label: "HEX",
      kind: "token-contract",
      address: ADDRESSES.hexToken,
      x: 69,
      y: 38,
      volumeScore: 72,
      balanceLabel: "$47.2k demo",
      activityLabel: "18 demo tx",
      status: "context",
      confidenceLabel: "Token contract",
      description:
        "Token contract node used to represent visible token balance and movement context.",
    },
    {
      id: "plsx-token",
      label: "PLSX",
      kind: "token-contract",
      address: ADDRESSES.plsxToken,
      x: 72,
      y: 55,
      volumeScore: 66,
      balanceLabel: "$32.6k demo",
      activityLabel: "16 demo tx",
      status: "context",
      confidenceLabel: "Token contract",
      description:
        "Token node used to preview how asset relationships group around a wallet.",
    },
    {
      id: "inc-token",
      label: "INC",
      kind: "token-contract",
      address: ADDRESSES.incToken,
      x: 59,
      y: 70,
      volumeScore: 42,
      balanceLabel: "$6.8k demo",
      activityLabel: "6 demo tx",
      status: "context",
      confidenceLabel: "Token contract",
      description:
        "Demo reward-token node tied to liquidity and farming-style activity.",
    },
    {
      id: "wpls-token",
      label: "WPLS",
      kind: "token-contract",
      address: ADDRESSES.wplsToken,
      x: 43,
      y: 74,
      volumeScore: 52,
      balanceLabel: "$11.4k demo",
      activityLabel: "11 demo tx",
      status: "context",
      confidenceLabel: "Token contract",
      description:
        "Wrapped native-token node for swap and liquidity route context.",
    },
    {
      id: "hex-pls-pair",
      label: "HEX/PLS LP",
      kind: "lp-pair",
      address: ADDRESSES.hexPlsPair,
      x: 23,
      y: 49,
      volumeScore: 61,
      balanceLabel: "$18.9k demo",
      activityLabel: "8 demo tx",
      status: "watch",
      confidenceLabel: "Liquidity pair",
      description:
        "Liquidity-pair node with inbound and outbound demo interactions.",
    },
    {
      id: "plsx-wpls-pair",
      label: "PLSX/WPLS LP",
      kind: "lp-pair",
      address: ADDRESSES.plsxWplsPair,
      x: 26,
      y: 74,
      volumeScore: 55,
      balanceLabel: "$14.1k demo",
      activityLabel: "9 demo tx",
      status: "watch",
      confidenceLabel: "Liquidity pair",
      description:
        "Second liquidity node for visual route density.",
    },
    {
      id: "hex-staking",
      label: "HEX staking",
      kind: "known-protocol",
      address: ADDRESSES.staking,
      x: 83,
      y: 69,
      volumeScore: 44,
      balanceLabel: "Stake context",
      activityLabel: "4 demo tx",
      status: "context",
      confidenceLabel: "Protocol contract",
      description:
        "Staking-related node shown as read-only research context.",
    },
    {
      id: "farm-contract",
      label: "Farm contract",
      kind: "known-protocol",
      address: ADDRESSES.farm,
      x: 69,
      y: 82,
      volumeScore: 36,
      balanceLabel: "Farm",
      activityLabel: "3 demo tx",
      status: "context",
      confidenceLabel: "Demo protocol label",
      description:
        "Farm-style node connected to liquidity activity.",
    },
    {
      id: "bridge-wallet",
      label: "Bridge-like wallet",
      kind: "wallet",
      address: ADDRESSES.bridge,
      x: 16,
      y: 30,
      volumeScore: 45,
      balanceLabel: "$24.3k demo",
      activityLabel: "6 demo tx",
      status: "review",
      confidenceLabel: "Demo label",
      description:
        "Wallet node used to preview inbound account context.",
    },
    {
      id: "spender-a",
      label: "Permit spender",
      kind: "spender",
      address: ADDRESSES.spenderA,
      x: 18,
      y: 67,
      volumeScore: 50,
      balanceLabel: "Allowance",
      activityLabel: "2 demo tx",
      status: "elevated",
      confidenceLabel: "Unknown spender",
      description:
        "Unknown spender-style node used to preview approval review language.",
    },
    {
      id: "spender-b",
      label: "Swap spender",
      kind: "spender",
      address: ADDRESSES.spenderB,
      x: 37,
      y: 88,
      volumeScore: 38,
      balanceLabel: "Allowance",
      activityLabel: "1 demo tx",
      status: "watch",
      confidenceLabel: "Unknown spender",
      description:
        "Second spender-style node for approval filtering.",
    },
    {
      id: "unknown-contract-a",
      label: "Unknown contract A",
      kind: "unknown-contract",
      address: ADDRESSES.contractA,
      x: 82,
      y: 30,
      volumeScore: 40,
      balanceLabel: "Contract",
      activityLabel: "3 demo tx",
      status: "elevated",
      confidenceLabel: "Unlabeled contract",
      description:
        "Unlabeled contract node shown with careful review-only wording.",
    },
    {
      id: "unknown-contract-b",
      label: "Unknown contract B",
      kind: "unknown-contract",
      address: ADDRESSES.contractB,
      x: 85,
      y: 51,
      volumeScore: 34,
      balanceLabel: "Contract",
      activityLabel: "2 demo tx",
      status: "watch",
      confidenceLabel: "Unlabeled contract",
      description:
        "A second unlabeled contract to make unknown-contract filtering visible.",
    },
    ...buildCounterpartyWallets(),
  ];
}

function buildCounterpartyWallets(): readonly VisualizerNode[] {
  return [
    ["wallet-01", "Counterparty 01", 8, 45, 26, "inbound"],
    ["wallet-02", "Counterparty 02", 10, 82, 22, "outbound"],
    ["wallet-03", "Counterparty 03", 18, 15, 24, "swap"],
    ["wallet-04", "Counterparty 04", 50, 12, 31, "route"],
    ["wallet-05", "Counterparty 05", 76, 14, 28, "token"],
    ["wallet-06", "Counterparty 06", 91, 41, 25, "contract"],
    ["wallet-07", "Counterparty 07", 93, 61, 26, "transfer"],
    ["wallet-08", "Counterparty 08", 78, 91, 27, "stake"],
    ["wallet-09", "Counterparty 09", 53, 94, 24, "lp"],
    ["wallet-10", "Counterparty 10", 18, 90, 23, "wallet"],
    ["wallet-11", "Counterparty 11", 7, 60, 21, "native"],
    ["wallet-12", "Counterparty 12", 12, 20, 19, "inflow"],
  ].map(([id, label, x, y, volumeScore, tag], index) => ({
    id: String(id),
    label: String(label),
    kind: "wallet",
    address: `0x${String(index + 1001).padStart(40, "0")}` as `0x${string}`,
    x: Number(x),
    y: Number(y),
    volumeScore: Number(volumeScore),
    balanceLabel: `$${(Number(volumeScore) * 410).toLocaleString()} demo`,
    activityLabel: `${Math.max(1, Math.round(Number(volumeScore) / 4))} demo tx`,
    status: index % 4 === 0 ? "review" : "context",
    confidenceLabel: "Wallet counterparty",
    description: `Sample counterparty wallet for ${tag} context in the local visualizer demo.`,
  })) satisfies readonly VisualizerNode[];
}

const DEMO_VISUALIZER_EDGES = [
  edge("edge-approval-pulsex", "center-wallet", "pulsex-router", "approval", "approval", "Allowance", "HEX", "$72,400 demo", 72400, 4, "18d ago", "3h ago", "review", ["tx-approval-pulsex"]),
  edge("edge-swap-pulsex", "center-wallet", "pulsex-router", "swap", "outflow", "Swap route", "PLSX", "$18,920 demo", 18920, 9, "14d ago", "42m ago", "context", ["tx-swap-1", "tx-swap-2"]),
  edge("edge-router-hex", "pulsex-router", "hex-token", "token-transfer", "internal", "Routed token", "HEX", "$34,600 demo", 34600, 8, "14d ago", "42m ago", "context", ["tx-swap-1"]),
  edge("edge-router-pair", "pulsex-router", "hex-pls-pair", "lp-interaction", "internal", "Pool route", "HEX/PLS", "$12,300 demo", 12300, 3, "9d ago", "4h ago", "watch", ["tx-lp-1"]),
  edge("edge-9mm", "center-wallet", "nine-mm", "swap", "outflow", "Alt DEX route", "WPLS", "$8,760 demo", 8760, 5, "7d ago", "2h ago", "context", ["tx-9mm-1"]),
  edge("edge-9mm-wpls", "nine-mm", "wpls-token", "token-transfer", "internal", "Wrapped route", "WPLS", "$8,760 demo", 8760, 5, "7d ago", "2h ago", "context", ["tx-9mm-1"]),
  edge("edge-phux", "center-wallet", "phux", "contract-call", "outflow", "Vault call", "PLS", "$6,400 demo", 6400, 2, "21d ago", "5d ago", "context", ["tx-phux-1"]),
  edge("edge-liberty", "liberty", "center-wallet", "token-transfer", "inflow", "Token inflow", "PLSX", "$5,920 demo", 5920, 2, "11d ago", "6d ago", "context", ["tx-liberty-1"]),
  edge("edge-hex-in", "hex-token", "center-wallet", "token-transfer", "inflow", "HEX balance", "HEX", "$47,200 demo", 47200, 18, "80d ago", "14m ago", "context", ["tx-hex-1", "tx-hex-2"]),
  edge("edge-plsx-out", "center-wallet", "plsx-token", "token-transfer", "outflow", "PLSX transfer", "PLSX", "$16,800 demo", 16800, 7, "30d ago", "2d ago", "context", ["tx-plsx-1"]),
  edge("edge-inc", "farm-contract", "inc-token", "token-transfer", "inflow", "Reward flow", "INC", "$6,800 demo", 6800, 4, "12d ago", "1d ago", "context", ["tx-inc-1"]),
  edge("edge-lp-add", "center-wallet", "plsx-wpls-pair", "lp-interaction", "outflow", "LP add", "PLSX/WPLS", "$14,100 demo", 14100, 3, "20d ago", "4d ago", "watch", ["tx-lp-2"]),
  edge("edge-lp-receipt", "plsx-wpls-pair", "center-wallet", "token-transfer", "inflow", "LP receipt", "PLSX-LP", "$14,100 demo", 14100, 3, "20d ago", "4d ago", "watch", ["tx-lp-2"]),
  edge("edge-stake", "center-wallet", "hex-staking", "contract-call", "outflow", "Stake action", "HEX", "$21,300 demo", 21300, 4, "70d ago", "9d ago", "context", ["tx-stake-1"]),
  edge("edge-farm", "plsx-wpls-pair", "farm-contract", "lp-interaction", "internal", "Farm route", "PLSX-LP", "$7,600 demo", 7600, 2, "18d ago", "5d ago", "context", ["tx-farm-1"]),
  edge("edge-bridge", "bridge-wallet", "center-wallet", "pls-transfer", "inflow", "Bridge-like inflow", "PLS", "$24,300 demo", 24300, 6, "16d ago", "1d ago", "review", ["tx-bridge-1"]),
  edge("edge-spender-a", "center-wallet", "spender-a", "approval", "warning", "Approval", "HEX", "$99,000 demo", 99000, 2, "25d ago", "3h ago", "elevated", ["tx-spender-a"]),
  edge("edge-spender-b", "center-wallet", "spender-b", "approval", "warning", "Approval", "PLSX", "$32,000 demo", 32000, 1, "9d ago", "9d ago", "watch", ["tx-spender-b"]),
  edge("edge-unknown-a", "center-wallet", "unknown-contract-a", "contract-call", "warning", "Unknown call", "PLS", "$2,240 demo", 2240, 3, "6d ago", "2d ago", "elevated", ["tx-unknown-a"]),
  edge("edge-unknown-b", "unknown-contract-b", "center-wallet", "token-transfer", "warning", "Unknown inflow", "TOKEN", "$380 demo", 380, 2, "3d ago", "3d ago", "watch", ["tx-unknown-b"]),
  edge("edge-wallet-01", "wallet-01", "center-wallet", "pls-transfer", "inflow", "Native inflow", "PLS", "$10,660 demo", 10660, 5, "44d ago", "5h ago", "context", ["tx-wallet-01"]),
  edge("edge-wallet-02", "center-wallet", "wallet-02", "pls-transfer", "outflow", "Native outflow", "PLS", "$9,020 demo", 9020, 4, "41d ago", "8h ago", "context", ["tx-wallet-02"]),
  edge("edge-wallet-03", "wallet-03", "pulsex-router", "swap", "internal", "Counterparty swap", "PLSX", "$7,300 demo", 7300, 3, "19d ago", "7d ago", "context", ["tx-wallet-03"]),
  edge("edge-wallet-04", "wallet-04", "phux", "contract-call", "internal", "Protocol touch", "PLS", "$4,920 demo", 4920, 2, "10d ago", "3d ago", "context", ["tx-wallet-04"]),
  edge("edge-wallet-05", "hex-token", "wallet-05", "token-transfer", "outflow", "Token movement", "HEX", "$3,880 demo", 3880, 2, "8d ago", "1d ago", "context", ["tx-wallet-05"]),
  edge("edge-wallet-06", "wallet-06", "unknown-contract-b", "contract-call", "warning", "Contract touch", "PLS", "$940 demo", 940, 1, "4d ago", "4d ago", "watch", ["tx-wallet-06"]),
  edge("edge-wallet-07", "unknown-contract-b", "wallet-07", "token-transfer", "warning", "Dust-like token", "TOKEN", "$41 demo", 41, 1, "2d ago", "2d ago", "watch", ["tx-wallet-07"]),
  edge("edge-wallet-08", "hex-staking", "wallet-08", "contract-call", "internal", "Stake cluster", "HEX", "$2,800 demo", 2800, 1, "12d ago", "12d ago", "context", ["tx-wallet-08"]),
  edge("edge-wallet-09", "wallet-09", "farm-contract", "lp-interaction", "internal", "Farm cluster", "INC", "$1,860 demo", 1860, 1, "11d ago", "11d ago", "context", ["tx-wallet-09"]),
  edge("edge-wallet-10", "center-wallet", "wallet-10", "pls-transfer", "outflow", "Native transfer", "PLS", "$6,260 demo", 6260, 2, "6d ago", "6d ago", "context", ["tx-wallet-10"]),
  edge("edge-wallet-11", "wallet-11", "center-wallet", "pls-transfer", "inflow", "Native transfer", "PLS", "$5,420 demo", 5420, 2, "5d ago", "1d ago", "context", ["tx-wallet-11"]),
  edge("edge-wallet-12", "wallet-12", "bridge-wallet", "pls-transfer", "internal", "Bridge cluster", "PLS", "$3,960 demo", 3960, 1, "16d ago", "16d ago", "review", ["tx-wallet-12"]),
] as const satisfies readonly VisualizerEdge[];

function edge(
  id: string,
  from: string,
  to: string,
  kind: VisualizerEdge["kind"],
  direction: VisualizerEdge["direction"],
  label: string,
  token: string,
  valueLabel: string,
  valueUsd: number,
  txCount: number,
  firstSeenLabel: string,
  lastSeenLabel: string,
  status: VisualizerEdge["status"],
  transactionIds: readonly string[],
): VisualizerEdge {
  return {
    id,
    from,
    to,
    kind,
    direction,
    label,
    token,
    valueLabel,
    valueUsd,
    txCount,
    firstSeenLabel,
    lastSeenLabel,
    status,
    transactionIds,
  };
}

const DEMO_VISUALIZER_TRANSACTIONS = [
  tx("tx-approval-pulsex", "edge-approval-pulsex", "3h", "Wallet", "PulseX router", "Unlimited demo", "HEX", "Approval", "Needs review"),
  tx("tx-spender-a", "edge-spender-a", "3h", "Wallet", "Permit spender", "$99,000 demo", "HEX", "Approval", "Elevated"),
  tx("tx-swap-1", "edge-swap-pulsex", "42m", "Wallet", "PulseX router", "$8,420 demo", "PLSX", "Swap", "Context"),
  tx("tx-hex-1", "edge-hex-in", "14m", "HEX token", "Wallet", "$4,900 demo", "HEX", "Transfer", "Context"),
  tx("tx-bridge-1", "edge-bridge", "1d", "Bridge-like wallet", "Wallet", "$24,300 demo", "PLS", "Transfer", "Review"),
  tx("tx-lp-2", "edge-lp-add", "4d", "Wallet", "PLSX/WPLS LP", "$14,100 demo", "LP", "LP interaction", "Watch"),
  tx("tx-unknown-a", "edge-unknown-a", "2d", "Wallet", "Unknown contract A", "$2,240 demo", "PLS", "Contract call", "Elevated"),
  tx("tx-inc-1", "edge-inc", "1d", "Farm contract", "INC", "$6,800 demo", "INC", "Reward", "Context"),
  tx("tx-stake-1", "edge-stake", "9d", "Wallet", "HEX staking", "$21,300 demo", "HEX", "Contract call", "Context"),
  tx("tx-wallet-02", "edge-wallet-02", "8h", "Wallet", "Counterparty 02", "$9,020 demo", "PLS", "Transfer", "Context"),
  tx("tx-spender-b", "edge-spender-b", "9d", "Wallet", "Swap spender", "$32,000 demo", "PLSX", "Approval", "Watch"),
  tx("tx-unknown-b", "edge-unknown-b", "3d", "Unknown contract B", "Wallet", "$380 demo", "TOKEN", "Transfer", "Watch"),
] as const satisfies readonly VisualizerTransaction[];

function tx(
  id: string,
  edgeId: string,
  timeLabel: string,
  fromLabel: string,
  toLabel: string,
  valueLabel: string,
  token: string,
  typeLabel: string,
  statusLabel: string,
): VisualizerTransaction {
  return {
    id,
    edgeId,
    timeLabel,
    fromLabel,
    toLabel,
    valueLabel,
    token,
    typeLabel,
    statusLabel,
  };
}

const DEMO_VISUALIZER_TIMELINE_ROWS = [
  ["24h", 62, "inflow"],
  ["2d", 46, "warning"],
  ["3d", 28, "warning"],
  ["4d", 58, "outflow"],
  ["5d", 36, "inflow"],
  ["6d", 42, "outflow"],
  ["7d", 30, "internal"],
  ["10d", 24, "internal"],
  ["14d", 72, "outflow"],
  ["18d", 38, "approval"],
  ["21d", 34, "outflow"],
  ["30d", 64, "inflow"],
  ["45d", 44, "inflow"],
  ["60d", 52, "approval"],
  ["90d", 70, "internal"],
] as const satisfies readonly (readonly [
  string,
  number,
  VisualizerTimelineBucket["direction"],
])[];

const DEMO_VISUALIZER_TIMELINE_MAPPED = DEMO_VISUALIZER_TIMELINE_ROWS.map(
  ([label, volume, direction]) => ({
    label,
    volume,
    direction,
  }),
) satisfies readonly VisualizerTimelineBucket[];

const DEMO_VISUALIZER_TIMELINE_EXPORT = DEMO_VISUALIZER_TIMELINE_MAPPED;

// Exported through the graph builder to keep the public API small.
const DEMO_VISUALIZER_TIMELINE: readonly VisualizerTimelineBucket[] =
  DEMO_VISUALIZER_TIMELINE_EXPORT;
